# Generated by Django 3.1.5 on 2021-04-29 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=60, verbose_name='empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevistado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellido')),
                ('email', models.EmailField(max_length=128, verbose_name='direccion email')),
                ('contraseña', models.CharField(max_length=60, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('duracion', models.PositiveIntegerField()),
                ('link', models.URLField(max_length=280, verbose_name='link reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Contact phone')),
                ('email_adress', models.EmailField(max_length=50, verbose_name='Email  Address')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevistador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellido')),
                ('rol', models.CharField(max_length=60, verbose_name='rol')),
                ('email', models.EmailField(max_length=128, verbose_name='direccion email')),
                ('contraseña', models.CharField(max_length=60, verbose_name='contraseña')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iterview.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('fecha', models.DateTimeField(verbose_name='fecha reunion')),
                ('lenguaje_programacion', models.CharField(max_length=60, verbose_name='nombre lenguaje de programacion')),
                ('entrevistado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iterview.entrevistado')),
                ('entrevistador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iterview.entrevistador')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iterview.reunion')),
            ],
        ),
    ]
