# Generated by Django 3.2.1 on 2021-05-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha reunión'),
        ),
        migrations.AlterField(
            model_name='agendar',
            name='nombre_agenda',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
    ]
