# Generated by Django 3.2.1 on 2021-05-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterview', '0002_auto_20210510_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar',
            name='lenguaje_programacion',
            field=models.CharField(default='python', max_length=60, verbose_name='Lenguaje programación'),
            preserve_default=False,
        ),
    ]
